### ISSUE TITLE
Removing featured image from Edit Post screen doesn't remove it from the Blog Posts screen

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/wp-desktop#114]
URL: Not applicable

What I expected: Removing featured image from the post in the Edit Post screen and updating the post should remove the featured image from the post in Blog Posts screen as well.

Steps to reproduce: Edit a post with a featured image and remove the featured image. Hit Update button. Go back to Blog Posts screen by clicking on Posts link at the upper left. 

What happened instead: The removed featured image still shows up on the post.

I tested this in both the Mac and Windows apps and noticed the same behavior.

Here is the screencast: https://cloudup.com/c8vxHWDcZLU demonstrating the problem.

**Comment by jasmussen** [comment]
Hi there, thanks for the excellent bug report.

Are you seeing this issue *only* in the desktop apps, or do you also experience it when using <a href="https://wordpress.com">the website</a>? If it's also an issue on the website, then it has to be fixed in Calypso itself. In that case, I would be grateful if you'd file this ticket here instead:

https://github.com/Automattic/wp-calypso/issues

Or I can move it for you, let me know. Thanks.

**Comment by chaitanyamsv** [comment]
Ah, I just checked and this problem exists in my browser as well: https://cloudup.com/cgdp_FspSHJ

So this not only in the desktop! 

Could you please move this bug to its rightful place :) Thank you!

**Comment by chaitanyamsv** [comment]
Closing this bug report as I reported this in Calyspo here: https://github.com/Automattic/wp-calypso/issues/3821
