### ISSUE TITLE
Linux: Rename wordpress-com-linux-x64-1-x-x-tar to wordpress-com-linux-x64-1-x-x.tar

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/wp-desktop#139]
Currently when the tar.gz is downloaded inside the .gz the file `wordpress-com-linux-x64-1-3-0-tar`is found. 

![screenshot_28-03-2016-10 49 23](https://cloud.githubusercontent.com/assets/150348/14085163/1be344a8-f4d3-11e5-8064-b5b4cd1e8c48.png)

In some version of Linux this cannot be opened as the file extension is missing:
![screenshot_28-03-2016-10 51 17](https://cloud.githubusercontent.com/assets/150348/14085147/07eb7d76-f4d3-11e5-9e60-149df3f4be08.png)
The solution is to rename `wordpress-com-linux-x64-1-3-0-tar` to `wordpress-com-linux-x64-1-3-0.tar` insde the `.gz` folder. 

![screenshot_28-03-2016-10 53 34](https://cloud.githubusercontent.com/assets/150348/14085198/581c903c-f4d3-11e5-9210-ee867c9daa0f.png)

**Comment by andersbateva** [comment]
This just happened to me and I came here to report. Very easy to fix, indeed.

**Comment by rachelmcr** [comment]
I confirmed that there is still a naming issue in the most recent release: `wordpress-com-linux-x64-1-6-0-tar.gz`

@sendhil Could you check the file naming for the next Linux .tar.gz release?

**Comment by sendhil** [comment]
Sure.

**Comment by sendhil** [comment]
@rachelmcr @BandonRandon - I think I have this fixed. Can you test with this version I've uploaded [here](https://cloudup.com/c4Ub0Svd7nR)?

**Comment by BandonRandon** [comment]
I did not have that problem with the latest version, but it looks like the fix was to remove the `.tar` and instead have the folder uncompressed. Here's what I now see with the beta download @sendhil  provided.
![screenshot_08-09-2016-22 31 54](https://cloud.githubusercontent.com/assets/150348/18376492/8a06f322-7614-11e6-9ca1-e6900204c06c.png)

When downloading the current production release which has the same version number, 1.7 (minus the beta-1) this is still an issue:
 
![screenshot_08-09-2016-22 36 28](https://cloud.githubusercontent.com/assets/150348/18376515/babfcb7e-7614-11e6-8dde-1e451623571c.png)

In theory if we use both `tar.gz` the final size of the download should be smaller, but I think leaving it uncompressed as in the beta link provided would also work just be a larger download.

**Comment by sendhil** [comment]
Ahhh thanks for the heads up @BandonRandon - will give it another go.

**Comment by BrookeDot** [comment]
Still a problem with 3.6.0. When downloading from `https://apps.wordpress.com/d/linux`  ( `https://public-api.wordpress.com/rest/v1.1/desktop/linux/download`) I'm given the file `wordpress-com-linux-x64-3-6-0-tar.gz` which opens up to `2.tar` in the file browser which then opens up to `WordPressDesktop-3.6.0`.

![screenshot_18-10-2018-09 18 26](https://user-images.githubusercontent.com/150348/47168931-0b959280-d2b7-11e8-89a5-32c21acfda3b.png)

If the download is renamed to `wordpress-com-linux-x64-3-6-0-tar.gz` then the folder opens up directly as `WordPressDesktop-3.6.0`

![screenshot_18-10-2018-09 20 41](https://user-images.githubusercontent.com/150348/47169017-4a2b4d00-d2b7-11e8-96f0-e3cf067b4cf1.png)

I decided to take a deeper look and see that the download links are being hardcoded in r181948-wpcom with the last few releases being packaged by @loremattei so this may be a limit of the current way files are being added.

Note this is on Ubuntu 18.04 now instead of Linux Mint but I expect the result to be the same on other platforms.

**Comment by BrookeDot** [comment]
[This behavior ](https://github.com/Automattic/wp-desktop/issues/139#issuecomment-431076097)is still happening with `wordpress.com-linux-x64-4.5.0.tar_.gz` so I wanted to make a note of it.

**Comment by designsimply** [comment]
@nsakaimbo would you be able to help with this one by chance? Is it a quick fix?

**Comment by nsakaimbo** [comment]
> ... would you be able to help with this one by chance? Is it a quick fix?

@designsimply Sure thing - will take a look and circle back.

**Comment by nsakaimbo** [comment]
Just a quick update on this:

It seems this might be (at least in part) specific to how the operating system handles `.tar.gz` assets.

Downloaded most recent release (v4.6.0) from `https://public-api.wordpress.com/rest/v1.1/desktop/linux/download`:

- Archive: `wordpress.com-linux-x64-4.6.0-tar_.gz`
- On mac, double-clicking extracts to the folder `WordPressDesktop-4.6.0` directly
- On Ubuntu, this extracts to `wordpress.com-linux-x64-4.6.0-tar`, which in turn contains the folder `WordPressDesktop-4.6.0`

I'm not very familiar with Linux quirks, but it seems by default Ubuntu extracts a `tar.gz` file to an intermediate folder (without the `.gz` extension), and in turn that folder will contain the target contents. What's odd is in some cases that intermediate folder may not have the same name as the parent.

@loremattei How is the `.tar.gz` archive at the link `https://public-api.wordpress.com/rest/v1.1/desktop/linux/download` generated? Does this logic live within the wp-desktop repo somewhere? Wondering if there's some way we can amend the logic to ensure that on Linux the `.tar.gz` extracts to the target folder directly.

cc: @designsimply

**Comment by BrookeDot** [comment]
Hi @nsakaimbo Thanks for your work on debugging this. I'm also curious how the archive is created. When I visit the endpoint in Firefox for Ubuntu I get a download for `wordpress.com-linux-x64-4.6.0.tar_.gz` I'm not sure where the `_` is coming from but removing it fixes the issue. 

This also seems to only be a problem with the GUI. When I run the extraction via the command line the `_` is ignored and I get the correct folder structure:

```
tar -xzvf wordpress.com-linux-x64-4.6.0.tar_.gz
WordPressDesktop-4.6.0/wpcom
...
```
If you remove the `_` to rename the folder the GUI extraction works ask expected. 

If we can't get rid of the `_` then I think we may just close this one out since it likely affects very few downloads.

**Comment by loremattei** [comment]
Hey @nsakaimbo! 

The archive is just the same archive that we release on GitHub, manually re-uploaded into WordPress.com. The issue with the name of the archive is related to the upload to WordPress.com, because the file is currently uploaded as a standard media resource and the `_` is automatically added by WordPress during the upload. I don't know if this can be easily patched.

Anyway, IMHO, we should just get rid of that logic, which is part of the old deployment logic that we used before starting the migration to relying on electron-updater's ability to check directly GitHub.

The work has stalled for a few months now, but basically the goal was to avoid all the manual stuff we have to do to release the app now and to update the endpoints to point to the archives on GitHub. 
By doing these changes, we'll solve also this issue.

**Comment by BrookeDot** [comment]
Same as with 3.6.0 with 6.6.0.
