### ISSUE TITLE
Mac: unable to scroll back up when viewing a single post

### ISSUE THREAD

**Issue by karmatosed** [Automattic/wp-desktop#148]
If I go into a post I am unable to scrollback up using my trackpad. I can use arrows to go back up.

**Comment by rachelmcr** [comment]
I just came across the same issue while viewing a single post in the reader. With both my trackpad and a mouse scroll wheel, I am unable to scroll up (but I can scroll down).

Tested on 1.3.1-beta, Mac OS X 10.11.4.

**Comment by jasmussen** [comment]
I've got more info now, and steps to reproduce. On Mac version 1.3.1-beta, do this:

- Open the app fresh, sign in, go to the reader. Scrolling up and down works fine.
- Open a long post to detail view in the reader, scrolls up and down fine. 
- Quit the app. The last position is stored as a cookie in the app.
- Open the app again, it should bring you back to the reader detail view you were just on. But now scrolling doesn't work. 

I'm suspecting the issue happens due to a conflict between the state-restoring JS we have, and this JS to prevent rubberband scrolling: https://github.com/Automattic/wp-calypso/tree/ea79491d21bd3946006bf58da6f2ddb4a116a6dc/client/lib/rubberband-scroll-disable

To reproduce, I disabled the rubberband-scrolling (`"rubberband-scroll-disable": false`) in `config/desktop.json` and built the app from scratch. Retraced the steps outlined above, and indeed yes it works when the rubberband scrolling is turned off in the config.

So it seems like the solution is to either tweak the rubberband-scroll-disable to work when the state restores you to a reader detail view (CC: @artpi), or to not restore state to detail view (CC: @batmoo). 

Or for timecrunch reasons, we can turn off the rubberband-scroll-disable for the time being.

**Comment by artpi** [comment]
I have to run now, because it's getting late in PL and tomorrow I'm starting my meetup travel.
So I vote for `"rubberband-scroll-disable": false` and dealing with it later :/

**Comment by mkaz** [comment]
Disabled for v1.3.1 release - will leave issue open so can be addressed later

**Comment by rachelmcr** [comment]
I continue to have trouble with this on Mac version 1.3.3. I tried these steps:

- Logged out and quit the app
- Opened the app and logged in
- In the Reader, I clicked on a post to open the detail view
- I scrolled down, and using both my mouse and my trackpad I can't scroll up again
- Using my arrow keys, I can scroll up and down fine.

**Comment by jessefriedman** [comment]
I'm experiencing the same exact issues as @rachelmcr on Mac 1.3.3

**Comment by jasmussen** [comment]
For what it's worth, I'm also on Mac, 1.3.3 release version (beta channel selected in preferenes), and I can't reproduce this.

**Comment by sendhil** [comment]
I can reproduce this on 1.3.3.

**Comment by sendhil** [comment]
I should add I can reproduce on a fresh install just on scrolling down, no need to engage in any kind of state restoration.

**Comment by eliorivero** [comment]
I'm also experiencing the same issue with v1.3.3 for OS X.

**Comment by cecilerainon** [comment]
Thought I'd add my comment as well: I've experienced scrolling (up only) issues while pulling up pictures in the media library (while editing a post), and in the left hand side sidebar (anywhere in the app).
