### ISSUE TITLE
Bug: Mac: App cannot start when it's already running for a different user account on same machine

### ISSUE THREAD

**Issue by skhg** [Automattic/wp-desktop#154]
I have multiple local user accounts on my Mac. When another user account is running the wordpress desktop app, it's not possible for me to start the app on my account. I get the error message in the attached screenshot.
![github wordpress bug](https://cloud.githubusercontent.com/assets/1479627/14394322/111072f8-fda2-11e5-88a6-422ab8ee9802.jpg)

**Comment by skhg** [comment]
To clarify, it doesn't matter what wordpress account the other user is logged in as, just that the app is already running under their mac account

**Comment by mjangda** [comment]
Ah, probably because we use a hard-coded port for the server. We'd need to switch to a list of ports (and pick one that's unused) to allow for concurrent instances across accounts.

**Comment by briankc** [comment]
Why was the fix for this reverted?

**Comment by astralbodies** [comment]
@briankc Sorry I totally dropped the ball and forgot to get back to you about addressing the issues we had. I had to revert because there was something that broke pretty badly with the changes. Can you try testing your PR against the latest develop branch and see if you can test and resolve any problems? I can't seem to find the log file I had saved during the release process when I reverted that PR. I remember it being very clear that there was a problem with connecting to the node instance.
