### ISSUE TITLE
Download Alpha

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#163]
Dear all, 

WP Desktop prompts me to download the Alpha but clicking on Download does not lead to any action.

Any advice?

Thankfully,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14843822/94d425ac-0c53-11e6-85be-5fc6c80ab44e.png)

**Comment by mjangda** [comment]
What version do you currently have installed?

**Comment by orschiro** [comment]
Dear @mjangda,

It's version 1.3.1 on Ubuntu 16.04. 

Warmly,

~Robert

![image](https://cloud.githubusercontent.com/assets/170947/14856454/635e19ca-0c98-11e6-87c1-2b0b615652aa.png)

**Comment by mkaz** [comment]
Confirmed this is an issue. For Linux, we typically take a user to the https://apps.wordpress.com/desktop/ page to pick which package version they need to download (.deb or .tar.gz) since we don't know the original way it was downloaded and installed.

However, this does not work for a beta since we only update that location with the stable version. So even if the download button worked (which right now it doesn't) it would only take you to the latest.

**Comment by mkaz** [comment]
This issue is fixed, it was all done on download site. Needed to enable beta support there.

The download prompt and button should work within the app.
Or you can go directly to https://apps.wordpress.com/desktop/?beta=1 to download the latest beta

**Comment by orschiro** [comment]
It works. Thank you @mkaz! :)
