### ISSUE TITLE
Feature Request: Share TO WordPress app from OS X menu

### ISSUE THREAD

**Issue by puccaso** [Automattic/wp-desktop#167]
Hi there guys, 
this would be something quite awesome
if i could right click and use the os/x share options directly to post a text or image to the wordpress app.. 

it would then ideally ask me which site i want to share too (if there are more than one) and hey-presto bobs your uncle!

any chance of something like this being added?

**Comment by lancewillett** [comment]
Great idea — we're working on something similar in the iOS app right now ([Sharing Extension](https://github.com/wordpress-mobile/WordPress-iOS/labels/Sharing)).

**Comment by txaqo** [comment]
ooo thats awesome.. 
iOS app, ok thats cool.. 
though wouldn't you guys have more coverage to get this enabled first on the Android app? because we can more or less run Android apps on ChromeOS/Chrome(with a bit of hacking)

Having said that, we can already share to WP from android, it just doesn't give us a Site selection, which can be a chore to switch. 

What could someone who knows nothing about coding do to help?

**Comment by lancewillett** [comment]
Here's the WordPress Android app GitHub repo: https://github.com/wordpress-mobile/WordPress-Android

**Comment by belcherj** [comment]
Will add this to the feature requests list. Closing for now.
