### ISSUE TITLE
Preferences: CSS flash for Spellcheck on Windows

### ISSUE THREAD

**Issue by supernovia** [Automattic/wp-desktop#177]
Since we can't display this option for Windows yet, can we fix it so it doesn't flash then disappear?

https://cloudup.com/cYiB4phjFhy

**Comment by jasmussen** [comment]
No matter the topic of spellcheck on Windows, the brief preferences Flash here, happens, presumably, due to some JS applying CSS to hide the preferences that aren't available on the Windows platform.

We can make that experience better by hiding those options by default using inline `display: none; ` CSS, and then *unhiding* it on the platforms that support it.
