### ISSUE TITLE
Editor Losing Authentication When Resuming from Suspended State

### ISSUE THREAD

**Issue by ghost** [Automattic/wp-desktop#188]
If the internet connection is not re-instantiated after being offline for a bit, it results in an error (Code 106?) Maybe you could add a internet connection check system and connect without manual intervention. 
Thank you!

**Comment by nsakaimbo** [comment]
Update: I don't believe the exact details of this error are relevant any longer, however we have had one report of a user (on Mac) resuming app usage from a long-suspended state:

> It seems to have lost my authentication over the weekend. it didn't tell me, but requests started failing. And unfortunately, the entire app is frozen; not because it's unresponsive, but because everything it tries to do fails due to auth. I quit the app and restarted and that resolved things.

A couple of immediate thoughts:

This is likely due to browser authentication credentials becoming stale (and would also likely happen in a browser as well). A couple of items to explore to improve the user experience:

(1) Add a "refresh" button to navigation control bar
(2) Investigate how to invoke a session cookie refresh from the Node process by way of an event that Electron fires when waking from a suspended state (if such an event exists - see https://www.electronjs.org/docs/api/power-monitor). The crude approach might be to trigger a browser/renderer reload on wake, but we might be able to refine the approach by fetching and replace existing cookies in the browser window session without an explicit reload of the window.
(3) As an additional refinement, session management logic in the Desktop app should also be revisited to ensure that old/new cookie values are compared and overriden accordingly.

**Comment by nsakaimbo** [comment]
Follow-up from a user for whom this issue is occasionally happening: it appears the call to `admin-ajax.php` is what fails.
