### ISSUE TITLE
Can't upload images to Mac desktop app

### ISSUE THREAD

**Issue by pizza0502** [Automattic/wp-desktop#198]
I've set up my self hosted WordPress to the latest WordPress Mac desktop app. I'm trying to upload media into my post and I get error.

Here is the screenshot:
https://www.dropbox.com/s/l16qs2lmm2egmzk/Screenshot%202016-06-20%2022.09.03.png?dl=0

<img width="1440" alt="screenshot 2016-06-20 22 09 03" src="https://cloud.githubusercontent.com/assets/1119271/16249004/3ac76926-3867-11e6-8f6c-e96304aa261e.png">

I've also increase my upload limit but still get the same result.

Please help, thanks!

**Comment by mkaz** [comment]
hi @pizza0502 - First can check if you can upload other files, using a regular browser and wp-admin? I want to check if it just in the desktop app. Sometimes permissions on the host does not allow uploading or creating new directories. More info on permissions at: https://codex.wordpress.org/Changing_File_Permissions

Since you're logged in and running, it looks like you have Jetpack installed, that would be the other thing to confirm that it is still connected and working. Thanks!

**Comment by rachelmcr** [comment]
Since we haven't heard back from you about this issue, I'm going to go ahead and close this. Please let us know if you are still having trouble!

If you also have trouble uploading media in a web browser at https://wordpress.com/ (not just in the desktop app) you can contact our Jetpack support team and we can do further troubleshooting there as well:

https://jetpack.com/contact-support/
