### ISSUE TITLE
Update not only Plugins?

### ISSUE THREAD

**Issue by orschiro** [Automattic/wp-desktop#227]
Dear all, 

Would it be possible to update Themes and Wordpress itself via Wordpress Desktop and not just Plugins?

Thankfully,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18120155/7c842dee-6f5e-11e6-90f3-1efb65e67bb1.png)

**Comment by rachelmcr** [comment]
Great suggestions! There is an open issue for bringing theme updates to Calypso here: https://github.com/Automattic/wp-calypso/issues/156

There is also an open issue to simplify updates (for plugins, themes, and WordPress core) in Calypso here: https://github.com/Automattic/wp-calypso/issues/2191

I'm going to go ahead and close this desktop-specific issue, since those enhancements in Calypso could be brought over to the desktop app if they are implemented.

**Comment by orschiro** [comment]
Thanks @rachelmcr! 

I will subscribe to these two. 

-Robert
