### ISSUE TITLE
Where is the draft saved?

### ISSUE THREAD

**Issue by supermansaga** [Automattic/wp-desktop#229]
I previously used the 2012 Windows Live Writer for writing on wordpress.com until I crashed my windows 10 and had to completely reinstall and found out that all my unpublished drafts were gone. I then switched to the wordpress.com app and realized it is the same as windows live writer in terms of not giving user the option for the location of the saved drafts. Could you please come up with v1.5.0 so that tragedy never occurs again for me or others out there? Thanks.

**Comment by rachelmcr** [comment]
Sorry to hear about your Windows Live Writer troubles! The WordPress.com desktop app is a bit different, though — instead of saving your posts locally (on your computer) the posts are saved on your site's server. If you ever uninstall the app, you can still find your posts by logging in to WordPress.com in a web browser:

https://wordpress.com/posts

**Comment by supermansaga** [comment]
I see the advantage now and have uninstalled Windows Live Writer and Open Live Write. However, the wordpress.com app is preferable if there is a "find" function within the editing post by pressing ctrl+f. thx

**Comment by rachelmcr** [comment]
Thanks for the suggestion! We are tracking that idea here: https://github.com/Automattic/wp-desktop/issues/35
