### ISSUE TITLE
Image Upload Windows 10 Multisite

### ISSUE THREAD

**Issue by Vyndariel** [Automattic/wp-desktop#254]
Hey,

I encounter the issue that I can't search my media library, as well as upload images from windows 10 desktop to my wordpress installations.

I couldn't find any information if I have to open ports in my router or anything. Adding image by URL works though.

**Comment by rachelmcr** [comment]
Thanks for the report! Could you please check to see if you have the same issue at https://wordpress.com/ in a web browser?

If so, there may be an issue with your site's Jetpack connection (rather than an issue in the app). In that case, please contact [Jetpack support](https://jetpack.com/contact-support/) directly and our team can help you there.

If the problem only occurs in the app, please comment here and we can reopen this issue for further investigation. Any additional details you can provide (for example, any errors or other things you see when you try to upload images or search your media library) will help the investigation.

**Comment by Vyndariel** [comment]
Hey,

sorry if I wasn't that clear, it's a selfhosted Wordpress

**Comment by rachelmcr** [comment]
Thanks. When a self-hosted WordPress is using the Jetpack plugin, you can manage it through the WordPress.com app or directly in a web browser at https://wordpress.com/ . If the problem persists in both places, that will tell us if the issue is with the Jetpack connection rather than the app itself.

**Comment by Vyndariel** [comment]
Hi,

it consists on both places. So as u stated it's a jetpack issue, am I right?

**Comment by rachelmcr** [comment]
Yes, that's right. You can [contact Jetpack support](https://jetpack.com/contact-support/) for assistance resolving that issue. :)
