### ISSUE TITLE
Text is too small with high resolution screen

### ISSUE THREAD

**Issue by rachelsquirrel** [Automattic/wp-desktop#299]
A user reports that when using the app on Windows 10 with a high resolution the text in the app is tiny and hard to read.

Possibly related to this https://github.com/Automattic/wp-desktop/issues/201

#3198817-t

**Comment by jacklenox** [comment]
Yep, the same issue. I haven't really been using the desktop app as a result of this.

**Comment by teerasej** [comment]
Vote for this. The app should provide setting to configure font's size and font family would perfect

**Comment by lancewillett** [comment]
If anyone here could add visuals to illustrate this, plus your version of the app — that would be super helpful. Thanks! #visox #visual-oxygen

**Comment by BlameDutchie** [comment]
Screenshot from a Mac 27", indeed it's pretty hard on the eyes after a while. I read that the app is basically Chrome than implementing Cmd+/Cmd- for zooming in/out should be possible?

![wp desktop app](https://user-images.githubusercontent.com/12746371/34173810-a4c9686c-e4ee-11e7-8ef6-f83b95d564a4.jpeg)

**Comment by jacklenox** [comment]
I'm using version 3.6 of the app (but I think this issue has been consistent since the app was first released). Here are two screenshots, the top one shows my default zoom level in the browser (120%) and how I like things to look. The bottom one is the app. In this scenario it's not a massive difference, but it's enough to have me sticking with using WordPress.com in the browser rather than using the app.

![screenshot from 2018-10-18 12-59-51](https://user-images.githubusercontent.com/751476/47150177-16abeb00-d2d6-11e8-8e08-003e3eea8d8e.png)

![screenshot from 2018-10-18 13-00-01](https://user-images.githubusercontent.com/751476/47150192-24fa0700-d2d6-11e8-99da-41be101ad46d.png)

**Comment by jonnyruzek** [comment]
I have a request in 1893940-zen to reduce the font size in macOS.

**Comment by pauljacobson** [comment]
I'd also like to see an option to change the text size in the app, generally. It's pretty small for me, and my aging eyes. Could we not surface Zoom controls through the app's View menu, perhaps?

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as the latest version of the app now includes Zoom controls. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
