### ISSUE TITLE
The request to undefined failed (code SELF_SIGNED_CERT_IN_CHAIN)

### ISSUE THREAD

**Issue by Richard0415** [Automattic/wp-desktop#326]
Cannot login the desktop app running on Windows 10 Enterprise from a corporate network.

Error Message (displayed in a red box and under the 'Lost you password?' link):

> The request to undefined failed (code SELF_SIGNED_CERT_IN_CHAIN), please check your internet connection and try again.

Please advise on what other info you'd like and I'll provide what I can.

**Comment by rachelmcr** [comment]
@Richard0415 If your corporate network intercepts SSL connections, you may see this error in the app. This is similar to another SSL error tracked in https://github.com/Automattic/wp-desktop/issues/152 — I'm going to close this issue since a solution to that issue should resolve this one. Thanks for reporting it!
