### ISSUE TITLE
Add search within a page/post

### ISSUE THREAD

**Issue by gibrown** [Automattic/wp-desktop#35]
I don't think this affects core wp-calypso because you can use the browser's search (command f) to search within the page, but in the desktop app there is no similar way to find something within the "page". For instance, I was composing a post that is 1700 words long. I want to find where in the page something is to go and edit it, and I have no way to find it. I need to re-read the whole post to re-find it.

Very frustrating.

**Comment by johngodley** [comment]
We looked at this before and bumped it over to Calypso as the find feature is not great, even in a browser:

https://github.com/Automattic/wp-calypso/issues/1180

I note also that Electron has since provided some additional functions:

https://github.com/atom/electron/blob/master/docs/api/web-contents.md#webcontentsfindinpagetext-options

This may help, although I suspect we'd have to implement the highlighting inside Calypso.

**Comment by apeatling** [comment]
I pretty much can't use the app for long posts because of the lack of find. I'd love for us to find a way to implement a solution here.

**Comment by supermansaga** [comment]
This shouldn't be hard to implement, although I am not a coder. Would love to have it asap. thx
