### ISSUE TITLE
Bug: Incorrect counts for Published/Draft posts

### ISSUE THREAD

**Issue by meowgabyte** [Automattic/wp-desktop#399]
**What I expected:** Published/Draft post counts on the top of the 'Blog Posts' section in app should reflect the total number of posts/drafts for that blog.

**Steps to reproduce:** 
1. Publish posts or create drafts in old version of Wordpress app, or using web interface.
2. Install Wordpress desktop app v3.1.0
3. View post counts under 'Blog Posts' section of app.

(Additional notes: I am using Windows 8.1, Wordpress app v3.1.0)

**What happened instead:** Initial post count was 0 for both published and drafts, and this count only increased if I published from the app itself. 

![Screenshot of post counts from web interface and desktop app](https://user-images.githubusercontent.com/7534644/34813045-5b17570e-f6e3-11e7-9e10-84565aa5c447.png)

**Comment by designsimply** [comment]
I checked my own test blog using WPDesktop 3.1.0, and my Posts/Drafts counts do not update automatically if I publish or save a draft post on the web _while the WPDesktop view is open_ but if I browse away and then back again or close and re-open the app then the counts are correct.

Just to make sure I've asked, and because the toggle isn't visible in the screenshots you provided, if the blog you are working with has more than one author can you verify that you have clicked the "Everyone" toggle on the Blog Posts page in the WPDesktop app? It's the first thing I thought of to check but can't tell whether you did or not from your report.

<img width="1124" alt="screen shot 2018-01-10 at wed jan 10 11 35 40 pm" src="https://user-images.githubusercontent.com/1119271/34813667-b27ffab6-f65f-11e7-916d-3b158cfb4e94.png">

**Comment by meowgabyte** [comment]
Hello, thanks for the quick check! Yeah the post counts are wrong even if I close and reopen the app (I also tried restarting and reinstalling, with no change in result).  Also thanks for checking about that, the blog in question only has one author (sorry I didn't include the toggle to save space). 

If it helps, some of my other sites are showing a correct post count using the same setup - it's only two of my more recent sites that have this problem. As far as I can tell, the only thing distinguishing them is that the sites with no problem were published entirely using the web interface, and were started earlier (>2 years ago).

**Comment by nickgallop** [comment]
I have a user also reporting this discrepancy in 1450116-zd-woothemes

**Comment by rachelmcr** [comment]
This was reported again in beta testing for 3.7.0-beta1 on macOS 10.14 (internal ref: p5T066-Hz-p2). The draft count was stuck at 0 even though one draft appeared in the app; the correct count was visible in a web browser.

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).
