### ISSUE TITLE
Notifications: Open more links in the app, when possible

### ISSUE THREAD

**Issue by jasmussen** [Automattic/wp-desktop#42]
Right now lots of notifications bounce you out of the app to the browser. Some of these could as well have opened in the reader, as they are either hosted WP.com links, or links to blogs you already follow.

**Comment by johngodley** [comment]
The notifications panel is an iframe outside of Calypso. In a browser it reloads the page rather than internally changing Calypso, but you don't really notice this as you are still in your browser.

I believe the notifications panel will eventually be built directly in Calypso, and so this problem will disappear.

We could potentially try and detect external requests for certain URLs and then feed these back into the app. It's a little bit error prone as a change in Calypso could break it.

**Comment by jasmussen** [comment]
> I believe the notifications panel will eventually be built directly in Calypso, and so this problem will disappear.

I feel like it's probably worth waiting until this happens, instead of building hacks and creating technical debt.
