### ISSUE TITLE
updating an article, wordpress client remove DIV with schema.org Data and Scripts. How to avoid this?

### ISSUE THREAD

**Issue by abioneperhobby** [Automattic/wp-desktop#422]
This is the article i can view in  my wordpress admin area

you can see schema.org data and a javascript tag that embed a video player.

![image](https://user-images.githubusercontent.com/2149815/36962739-0c7c73a8-2051-11e8-8bb8-1223ef22983c.png)

Now i edit the article with desktop app and i press update.

![image](https://user-images.githubusercontent.com/2149815/36962821-53bc56e8-2051-11e8-83d0-175cbc5d4597.png)

after the update, schema.org div and embed was deleted.

![image](https://user-images.githubusercontent.com/2149815/36962942-bd22351c-2051-11e8-9ac6-df152c2e2e23.png)

what's wrong?

thanks

**Comment by brbrr** [comment]
Hi @abioneperhobby 

I've just tested it - and the desktop app did not remove javascript code **if you editing in HTML mode**. This issue is related to Calypso, not WP-Desktop itself. Please report it here: https://github.com/Automattic/wp-calypso


I'm going to close this issue since it isn't related to WP-Desktop.
