### ISSUE TITLE
Quit app is disabled when having unsaved changes in editor

### ISSUE THREAD

**Issue by adlk** [Automattic/wp-desktop#459]
#### Steps to reproduce
1. Open App (obviously)
2. Edit a Post or Page
3. Edit the content
3. Try to quit the App via Menu or Shortcut. 

#### What I expected
If I have unsaved changes, display the dialog:
> You have unsaved changes. Are you sure you want to leave this page?

If not cancelled, quit app.

#### What happened instead
The unsaved changes dialog did not appear like it would when I try to click "Close" in the editor window and quitting the app was cancelled.

#### App Version / OS version
3.3.0 / macOS 10.13.5

**Comment by adlk** [comment]
@seanbashaw,sure, you're welcome. Do you already have an idea on how to approach this?

**Comment by lakellie** [comment]
Just dropping a note here that this still seems to be happening - noticed it when testing the latest beta version 4.2.0

**Comment by designsimply** [comment]
Tested and confirmed that I cannot quit the app by going to WordPress.com > Quit or pressing `Command + Q` if I have the block editor open and there are unsaved changes. I found that this problem only happens when using the block editor and not the classic editor. ([1m16s](https://cloudup.com/cwyNUr4HmaM))

![Screen Shot 2019-06-10 at 3 56 41 PM](https://user-images.githubusercontent.com/1119271/59230101-a1a96080-8b99-11e9-87de-5cafcf169406.png)
<sub>Tested with WPDesktop 4.2.0-beta1 on macOS 10.14.5.</sub>

**Comment by belcherj** [comment]
This is no longer an issue.
