### ISSUE TITLE
[macOS] Followed sites: Manage button overlap on medium-sized windows

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-desktop#555]
#### Steps to reproduce
1. Make the window a bit larger than mobile-width.
2. See the Manage button overlapping the "Followed Sites" stream.

#### App Version / OS version
App version: 3.8.0
OS version: macOS 10.14.3

#### Screenshot / Video
![Image](http://cld.wthms.co/ddpjyk+)

![Video](http://cld.wthms.co/pCJgVT+)

**Comment by rachelmcr** [comment]
@tbradsha Thanks for reporting this! I see the same behavior on Calypso on the web. Since the desktop app just packages Calypso, any bugs that happen in both the app and web need to be fixed in Calypso first, and then the desktop app will pick up those changes.

Could you please report this in https://github.com/Automattic/wp-calypso/issues (if there isn't already an issue for it)?
