### ISSUE TITLE
Lost content in draft after publishing on Mac Desktop App 4.0.0

### ISSUE THREAD

**Issue by rezzap** [Automattic/wp-desktop#575]
A user reported in 1903586-zen having lost all content they had updated and saved in a draft when clicking publish after having updated to the most recent version of the app.

#### Steps to reproduce
1. Create a new post and save as draft.
2. Update the app to the latest version.
3. Return to the post to continue editing. The content of your post should still be there, then you can add additional content. (repeat this as needed closing the app and returning to it after 'saving')
4. Hit publish.

#### What I expected
I would expect the latest content added to be displayed in the post.

#### What happened instead
All content was removed and the saved changes done since the update which were available before hitting publish (even after closing and re-opening the app multiple times) were lost.

#### App Version / OS version
Desktop version 4.0.0 / macOS 10.14.3

**Comment by designsimply** [comment]
I completed the following steps using WPDesktop 3.9.0 and upgrading to WPDesktop 4.0.0 on macOS 10.13.6. I used a WordPress.com Free plan for this test.

1. Uninstall WPDesktop 4.0.0 by dragging it to the trash and emptying the trash.
1. Install WPDesktop 4.0.0 (I used the .dmg from [here](https://github.com/Automattic/wp-desktop/releases/tag/v3.9.0)).
1. Create a new draft with text and images.
1. Quit the WPDesktop app and re-open it.
1. Upgrade to WPDesktop 4.0.0.
1. Edit the draft created in step 3.
1. Quit the app.
1. Re-open the app.
1. Edit the draft created in step 3 again.
1. Publish the post.

Results: the post and all of the new content were published normally. 

I tried the test twice with the same results:

1. [Spilt Milk](https://madefortesting190318.wordpress.com/2019/03/26/spilt-milk/) ([revisions](https://madefortesting190318.wordpress.com/wp-admin/revision.php?revision=27)) 
1. [Dumplings](https://madefortesting190318.wordpress.com/2019/03/26/dumplings/) ([revisions](https://madefortesting190318.wordpress.com/wp-admin/revision.php?revision=32))

@astralbodies may I ask for help with a 2nd check on this? @rachelmcr could you help me check if there is there anything I've missed in the testing steps?

**Comment by rachelmcr** [comment]
From the description of the issue, this sounds like a Calypso issue rather than something specific to the desktop app. In particular, it sounds similar to some recent reports on this issue:

https://github.com/Automattic/wp-calypso/issues/20265

I'm going to close this issue in favor of that one, since there's nothing I can see that indicates this case is specific to the desktop app.

Reports seem to note that this is happening with the classic editor, which is the only editor currently available in the desktop app and the one this user also has as their default on the web. It sounds like switching to the block editor may be something to try here — the block editor is currently only available on the web but we'll be beta testing it in the desktop app soon in hopes of releasing it here as well.
