### ISSUE TITLE
Update Electron to the latest version

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#588]
We need to update the `electron` package to the latest version.

Internal ref: C7YPUHBB2/p1554976022178600-slack-team-calypso

**Comment by loremattei** [comment]
An update on this issue. I worked a bit on it on this branch: https://github.com/Automattic/wp-desktop/tree/update/electron-4.2. 
The app builds and seems to work well on all the platforms, but tests are still failing on CI. 
Watching the recorded videos, it seems that Calypso fails to start when the app is run by the test driver. 
I'm now wondering if it's due to some race conditions between Electron background and renderer threads, because the tests usually run without issues on my local machine and usually pass if you re-run them on the CI using SSH.

**Comment by nsakaimbo** [comment]
I just updated Electron from v1.7.16 to v4.2.9. Please refer to the following PRs:

- Upgrade Electron: #662 
- Update Circle Config: Remove Windows: #663 
- Update Circle Config for Linux: #664 
- Add e2e utility script: #668 
- Add AppVeyor Script: #669

### Summary/Highlights:

- The application is functional and CI tests are passing. 🎉 
- For now, we are constraining the version of Electron to match the version of Node required by Calypso.
- We are migrating `electron-spellchecker` from prebuilds to compiling from source, because the prebuild repo is stale and not compatible with newer versions of Electron.
- Because we are dropping prebuilds, we will need to compile for all platforms in their native environment (Circle for Linux and Mac, AppVeyor for Windows).

### Outstanding Issue

Unfortunately, upgrading Electron makes it so the spellchecker loses functionality due to an incompatibility with Calypso. This will require further research, and possibly involve making changes to the spellchecker source and/or working with Calypso to figure out a workaround.

**Comment by nsakaimbo** [comment]
Electron upgraded to v4.2.9 in #757 -- closing this out.
