### ISSUE TITLE
Any links to wp-admin open in browser, rather than the app

### ISSUE THREAD

**Issue by jonnyruzek** [Automattic/wp-desktop#590]
When editing my site in the app, some links open in my default browser instead.

#### Steps to reproduce
1. _My Sites > Switch Site_ to any site with a Business plan upgrade with at least 1 third-party plugin/theme installed
2. Click on _Site Pages > Add_

#### What I expected
I expected to be able to edit my pages/posts within the app

#### What happened instead
The app open my default browser to a Calypsofied version of wp-admin

#### App Version / OS version
Version 4.1.0-beta3 release

#### Context / Source
1963289-zen

**Comment by rachelmcr** [comment]
Thanks for the report! This is the current expected behavior of the desktop app. The app only includes Calypso itself; any links to pages outside of Calypso (including wp-admin) opens in a web browser.

This specific case (with the Calypsoified wp-admin editor) should be improved once Gutenberg is available for Atomic and Jetpack sites within Calypso, and that's launched in the app.

**Comment by designsimply** [comment]
> This specific case (with the Calypsoified wp-admin editor) should be improved once Gutenberg is available for Atomic and Jetpack sites within Calypso, and that's launched in the app.

We are now tracking this in #640.
