### ISSUE TITLE
How to allow self-hosted WP authors to login & post through this app?

### ISSUE THREAD

**Issue by nabtron** [Automattic/wp-desktop#591]
How to allow self-hosted WP authors to login & post through this app?

Right now only the owner of the blog, who used his wordpress.com account to connect jetpack to the self hosted blog, can login to the mobile or desktop app and make a new post. 

How can I allow the users created on the website (not wordpress.com) to login via app and create posts.

**Comment by designsimply** [comment]
If the author on the self-hosted site does not yet have a WordPress.com account:

1. Log in to the self-hosted site.
1. Go to Jetpack > Dashboard.
1. Click the "Create Account" button.
1. Follow the prompts to finish account creation and then move to the next set of steps below.

If the author on the self-hosted site already has a WordPress.com account:

1. Log in to the self-hosted site.
1. Go to Jetpack > Dashboard.
1. Scroll down to "Account connection".
1. Click the "Link to WordPress.com" option.
1. Follow the prompts to authorize a connection.

For future help request questions about how to use the app or if you get stuck with any of these steps, please use the question mark icon (?) at the bottom right in the app so the support team can help you through that channel and so we can keep the GitHub repository for bug reports and enhancement requests. If you find a bug along the way and would like to report it here, please create a new issue with steps to reproduce and someone will help you test it. If you're not sure whether an issue is a bug or not or where to report it, start with the support team and they should know how to help direct you. Thank you!

**Comment by nabtron** [comment]
Isn't it a bug that a user of the site can not post without creating another account? It's not practical to ask all authors of a public community to make accounts on a third party website just to publish using the app.

**Comment by designsimply** [comment]
In this case, the app is `WordPress.com for Desktop` and it was specifically made for WordPress.com. It is also possible to use it on a site not hosted at WordPress.com by connecting through Jetpack, and doing that requires each person who would like to use the app to also have a WordPress.com account. It isn't a bug, it's how the app was designed and part of the reason is that some of the features and benefits, such as stats and notifications among other things, are made available in the app but require a connection to WordPress.com in order to leverage the back end tools from that platform.
