### ISSUE TITLE
Why self hosted site have to install jetpack?

### ISSUE THREAD

**Issue by yduke** [Automattic/wp-desktop#601]
Sorry to bother, but did you guys know Wordpress.com had been blocked in China and many other countries?
Jetpack is good, I know, but as our server can not reach wordpress.com jetpack can help nothing but delaying websites and make visitors gone.

See this  [https://github.com/Automattic/jetpack/issues/3758](https://github.com/Automattic/jetpack/issues/3758)

Why force everyone to install jetpack? Not everyone lived in US.
I love Wordpress, years ago when I know official app releases, I was very excited, but unfortunately I lived in china, jetpack was never an option.

I believe this app will be great  if jetpack is not required like iOS client or maybe it can be optional.

**Comment by dmsnell** [comment]
Thanks for the comment @yduke. The desktop app we have built relies on a number of features and API endpoints provided by Jetpack. At the there are no plans to provide support for general WordPress websites without Jetpack because that would involve a pretty big effort and we have other priorities taking our time at the moment.

The mobile app on the other hand _does_ support managing WordPress sites without Jetpack. Hopefully some day we'll get there with the desktop app too!

**Comment by yduke** [comment]
`there are no plans to provide support for general WordPress websites without Jetpack`

Disappointed.
