### ISSUE TITLE
diferences in plan itens between site and desketop app

### ISSUE THREAD

**Issue by vannox** [Automattic/wp-desktop#603]
there are missing itens in the eCommerce plan when you look at it in the site version and the desktop app

![WPitensPlan](https://user-images.githubusercontent.com/17816815/58435970-6be48200-8099-11e9-83e7-8c762948a001.jpg)

**Comment by designsimply** [comment]
Thanks for the report! A new release of the desktop app is typically done every couple weeks, and WordPress.com is done with continuous deployments. Because of this, the app may be a little out of sync for an update like that but should catch up within a week or so at the most. 

I tested with 4.2.0-beta1 just now, which you can get from [the releases page](https://github.com/Automattic/wp-desktop/releases/tag/v4.2.0-beta1), and I can see the updated descriptions there:

![Screen Shot 2019-05-30 at 6 26 39 PM](https://user-images.githubusercontent.com/1119271/58673454-adc72f80-8308-11e9-8741-66eb9ac41122.png)
<sub>Tested with WPDesktop 4.2.0-beta1 on macOS 10.14.5.</sub>
