### ISSUE TITLE
Plugins section is giving a Jetpack Manage error

### ISSUE THREAD

**Issue by tbradsha** [Automattic/wp-desktop#633]
#### What I expected
The ability to edit plugins on a site hosted by WordPress.com.

#### What happened instead
Received an "Enable Jetpack Manage" message.

#### App Version / OS version
OS: Windows 1809 (Windows 10 Home 10.0.17763 build 17763)
App version: 4.1.0

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/32492176/59803959-e58b1c80-92a1-11e9-9445-2273afbc2603.png)

#### Context / Source
Reported here: 13517970-hc

Note that on my end with a different test site hosted at WordPress.com, I'm not seeing the plugins section at all. As such, I'm not sure if the plugins section shouldn't show at all, if it should show but not have the error, or if there's an additional bug and it should show always show the plugins section.

**Comment by rachelmcr** [comment]
Thanks for raising this issue! A new version of the app (4.2.0) was just released. I went to test this there, and I see that the Plugins section has been removed, so this error won't appear anymore.

However, I'm not sure that was an intentional change for the app, so I'm following up about that in https://github.com/Automattic/wp-desktop/issues/636.
