### ISSUE TITLE
Can't edit posts/pages from the desktop app

### ISSUE THREAD

**Issue by feastoftravel** [Automattic/wp-desktop#646]
#### Steps to reproduce
1. Open Wordpress desktop app
2. Go to Site > Posts
3. Click on a post

#### What I expected
To go to the edit page of the app.

#### What happened instead
It redirects me to the wp admin webpage.

#### App Version / OS version
Version 4.2.0 / Version 10.14.5

**Comment by rachelmcr** [comment]
Thanks for the report, @feastoftravel! Are you using the Jetpack plugin on your site and the block editor (Gutenberg) for your posts/pages? If so, that's the current expected behavior for the app.

The desktop app doesn't yet support the block editor for Jetpack sites, so for now you'll be directed to the browser. You can follow https://github.com/Automattic/wp-calypso/issues/32048 for progress enabling it in the app.

If you have a WordPress.com site and are still seeing this behavior, please let us know your site address and we can investigate further.

**Comment by feastoftravel** [comment]
Hi @rachelmcr , thanks for your reply. I am using Jetpack and Gutenberg. Is there a way to revert to the previous editor until the block editor is enabled in the app?
Best,
Guillem

**Comment by rachelmcr** [comment]
One way to revert to the previous editor is to visit https://wordpress.com/ in a web browser and open the editor there. You can open the 3-dot menu in the top right corner of the editor and select "Switch to Classic Editor":

![Screenshot 2019-07-11 12 38 09](https://user-images.githubusercontent.com/8658164/61048147-f2022100-a3d8-11e9-91b1-a11f33e463a2.png)

That selection will be used for both WordPress.com web and the desktop app, so when you next use the app it will open the classic editor. (If you already had the desktop app open, you may need to close and reopen it for that preference to be used.)
