### ISSUE TITLE
WordPress.com ran into an error! (code 0) when trying to view site

### ISSUE THREAD

**Issue by lakellie** [Automattic/wp-desktop#648]
The user is able to successfully use the app to edit pages, view the Reader, etc. but when they click to view their site, they get this error: https://snag.gy/mldvNP.jpg

Then after closing that out, they see this: https://snag.gy/6wArUj.jpg

They mentioned already trying the proxy solution mentioned for similar issues, but it did not resolve their issue. They also tried reinstalling the app. App and OS are up to date. I am not sure what else to suggest to the user. Any ideas? 

Ticket: #2183847-zen

#### App Version / OS version
Mac desktop app 4.2.0 / Mojave 10.14.5

**Comment by designsimply** [comment]
Adding the screenshots here to keep them in GitHub (you can drag and drop them into an issue for safe keeping!) and also noting the onscreen error in text so the issue is searchable in the future:

> Uh oh!
> WordPress.com ran into an error! (code 0)
> Using a proxy?

![mldvNP](https://user-images.githubusercontent.com/1119271/61549891-7292d400-aa0e-11e9-8653-85352d92519e.png)

> Uh oh. Page not found. 
> Sorry, the page you were looking for doesn't exist or has been moved.

![6wArUj](https://user-images.githubusercontent.com/1119271/61549903-77578800-aa0e-11e9-933e-96b7d3f5a206.png)

Adding some relevant details from the original case reported via the internal help request:

* MAC desktop app v 4.2.0 Running Mojave 10.14.5
* Site type: WordPress.com Premium Plan

And about the error number:

> Was it saying error 330 before? And now it says 0?
> Yes, 0

There is a list of error codes at https://code.google.com/p/chromium/codesearch#chromium/src/net/base/net_error_list.h and I'm noting the error for 330 in case that's relevant to developers later:

> // Content decoding of the response body failed.
> NET_ERROR(CONTENT_DECODING_FAILED, -330)

Please try the following troubleshooting steps:

1. If you are using a proxy, go to System Preferences > Network > Advanced > Proxies, find "Bypass proxy settings for these Hosts & Domains", add `127.0.0.1` and click "OK".
1. If you are using custom DNS servers at System Preferences > Network > Advanced > DNS, try changing them to something else. ([ref](https://github.com/Automattic/wp-desktop/issues/334#issuecomment-365541576))
1. Close the app.
1. Go to ~/Library/Application Support/
1. Delete the "WordPress.com" directory.
1. Re-open the app and try to view your site.

> The app opens fine, but when I try to view my site from the app it crashes.

If none of the troubleshooting steps above help to resolve the problem, can you please describe the exact steps that are being taken to try to view the site? For example, are you going to My Sites then clicking on the site name and then it crashes at that point, or does it only crash after you click the "Visit Site" button at the top right? Also, are you using any Antivirus software and does the problem go away if you temporarily turn that off as a quick test?

**Comment by lakellie** [comment]
Closing this one out, as user never wrote back after we passed along the above troubleshooting steps.
