### ISSUE TITLE
Bug: User changed font setting in app making it too large to read.

### ISSUE THREAD

**Issue by sstabrizi** [Automattic/wp-desktop#693]
A user just said that he clicked something in the app on a Surface 4 tablet and that the text is now way too large to read in the app. He stated the following:

"How do I make my print font smaller on this word press app. I was working with wp, and must have hit a button that makes everything too large. How make it normal again. it is a surface 4 computer."

I've sent a follow-up email asking for him to clarify the following:

- Can you please verify they're running Windows 10.
- What version of the WordPress.com Desktop app are you running?
- Have you made any adjustments to the system font settings on the Surface 4?
- Which screen(s) are displaying the fonts way too large in the desktop app, all of them or just certain ones?
- Would it be possible to send us a screenshot showing the problem? 

Our initial thought is that this is a device/OS thing, but we wanted to create this to track the issue.

2463872-zen

**Comment by api-gov-network** [comment]
Spam

**Comment by rachelmcr** [comment]
Thanks for this report! Since our hunch is that it's an issue with the device/OS and not the app, and we haven't heard back about it for 2 weeks, I'm going to go ahead and close this issue. If the user can provide more details that point to it being an issue in the app, please update the issue and reopen it and we can take another look.
