### ISSUE TITLE
Block Editor not working

### ISSUE THREAD

**Issue by tecumsa** [Automattic/wp-desktop#721]
First off, is there a tutorial on the block editor, if I ever get it working?

Now, the issue. I clicked on the link to try out the block editor and ended up in a near-blank screen. Took support and I nearly half an hour to get back to the regular editor, and it wasn't an easy process. Screen shot attached.

#### Steps to reproduce
1. Went into the Posts section of my blog
2. Selected and copied one of my posts
3. Opened the copy to edit
4. Clicked on the Try the Block Editor
5. Bingo, the attached screen.
![Screen Shot 2019-12-08 at 8 19 50 PM](https://user-images.githubusercontent.com/58710687/70579303-24799b00-1b7e-11ea-8a07-25aa1516300b.png)

**Comment by rezzap** [comment]
Hi there!

We have a support document on the WordPress Block Editor which you can find here: https://en.support.wordpress.com/wordpress-editor/

It sounds like the issue you're experiencing is specific to your setup, but we're having trouble finding the details of the interactions you've already had with support to look into this further. Could you send a new email to WordPress.com support at help@wordpress.com with the details of your site address (URL) and the version of the app you are using? We'll be able to investigate this further for you with those details. You can link to this thread in the reply or add the site URL here if you would prefer.

As a first step, you could try activating a different theme on your site to see if the same problem continues. This will help us narrow down where the issue coming from. 

Thank you!

**Comment by designsimply** [comment]
I tried testing using the steps provided today, but the block editor opened normally for me without any problems. I believe the issue could be related to the content specifically or the site configuration/setup (as rezzap mentioned in her comment earlier). Note: I tested using WPDesktop 4.7.0-beta1 on macOS 10.14.6.

I feel this case needs more troubleshooting at the support level and is not yet ready to be reported as a bug since it cannot be replicated easily given the steps provided. Please contact support directly at help@wordpress.com (if you haven't already) and provide a link to this issue https://github.com/Automattic/wp-desktop/issues/721 for background. Trying the same steps again with one of the default themes enabled would be a good next step, if you're willing to give that a go please do that and report the results to us when you contact support. If it does turn out to be a bug, we can re-open this issue—however, more information is definitely needed before we can move forward here in the bug repository. Thank you so much for reporting the issue and I hope to see more from you about the case so we can get to the bottom of this!
