### ISSUE TITLE
Cannot verify on Wordpress desktop for Mac

### ISSUE THREAD

**Issue by slvrdlphn** [Automattic/wp-desktop#730]
Ever since the last desktop app update I have not been able to use Wordpress except from the browser because it would not allow me to login.  Every time I put in my username and password (which works on the browser) it asks me to verify and two options are given.
- verify using authenticator
- verify via SMS

Since authenticator does not seem to work I tried via SMS.  When I click on that the screen tells me to PLEASE ENTER YOUR CREDENTIALS ... which have already been input in the first place. 

I've tried just restarting the app, deleting it and reinstalling it, nothing seems to work.  But I have no problem accessing my site using the browser or MarsEdit.  FYI, I am currently on Catalina but the problem happened while I was still on Mojave.

Here is a screenshot of my Wordpress desktop app error.
![image](https://user-images.githubusercontent.com/5617193/71481066-530e9b80-2837-11ea-948c-67e2480da864.png)

**Comment by damiannep** [comment]
I'm able to authenticate with WordPress.com version 4.6.0 release on Mac OS 10.15 (Catalina). What version of Mac OS and the WordPress.com app are you using?

**Comment by slvrdlphn** [comment]
I am using Mojave and was trying to log onto the latest version of the wordpress desktop app.  it used o work for me but when it upgraded it just stopped doing so.

Penny

**Comment by rachelwinspear** [comment]
I am still on Mojave, version 10.14.6, with the WordPress.com App version 4.3.0, I am able to login and verify with the code.
I have just updated the WordPress.com App to version 4.6.0 and have also been able to login using the verification code, I am using the Google Authenticator App.
I wasn't able to replicate this issue.

**Comment by slvrdlphn** [comment]
I’ve tried uninstalling the app and reinstalling it.  I even factory reset my laptop and I still encounter the same problem.  I have no problem accessing Wordpress from the browser.  It is just the app that is giving me problems.

When I click on send code via text it does not send the code to my phone via SMS as I expect it to.  I’ve tried waiting for a long time (30 minutes even) to no avail.

When I try to authenticate using my phone app nothing happens either.


Penny

**Comment by damiannep** [comment]
Hi Penny, I have a suggestion. Can you wait for the first authentication code in your Authentication app to expire and try the second one or third one to see if that works please?

**Comment by designsimply** [comment]
> I tried via SMS. When I click on that the screen tells me to PLEASE ENTER YOUR CREDENTIALS ... which have already been input in the first place.

I tested and I see the problem you described with the "Send code via text message" option and I found that issue was reported at https://github.com/Automattic/wp-desktop/issues/701 and has been fixed, and I believe the update for that will come out in the 4.7.0 release.

I also tested two-factor login in the WPDesktop 4.6.0 app using macOS 10.14.6 (Mojave) just now and I found that I was able to log in using the verification code from the Authy authenticator app without any problems. 

In regard to the problem you are having with the authenticator login flow, because three separate people have tested two-factor authentication using the WPDesktop app and reported back here that it works for them, I'm wondering if there's something wrong with your account or if it's possible that you've mixed up which authenticator app to use (something I have done before by mistake!). It sounds to me like this case would benefit from taking with a happiness engineer directly. If you're willing to get help from the support team to troubleshoot this further, you can use https://wordpress.com/help/contact and include the username you are trying to log in as and as much detail you can think of about the time you set up two-factor authentication.

**Comment by designsimply** [comment]
In addition to damiannep's suggestion to wait for the first authentication code in your Authentication app to expire and try the second one or third one, you might also want to try one of your backup codes to see if they work. Did you save backup codes when you set up your two-factor authentication originally?

**Comment by designsimply** [comment]
Another idea, since you said you are able to log in using the same Authenticator app with a browser on the same computer but not with the Desktop app, do you have any local firewall software or security settings on that computer which could be interfering? 

Is there any chance you could try with a different computer on the same network? That would rule out an issue at the local network level.

**Comment by slvrdlphn** [comment]
No local firewall and no special security settings.
The app used to work with no issues until the latest update.
It won’t authenticate via SMS or via wordpress app.

There isn’t any other computer I can use at home as everyone else is on a tablet.  I can’t install in the computers at work without going through ITD.

The wordpress app works perfectly fine on my tablet, iPad, and phone, though.
I will try it on my sister’s laptop at her place, though.  She is running on Windows.  If it works for her then it is really just me.

Penny

**Comment by nsakaimbo** [comment]
Update on this thread: we're closing this issue as we expect this and a whole host of other issues to be resolved by the new version of the application (v7.0.5) that was just released. The latest build can now be downloaded at the WordPress Desktop landing page [here](P7jrAc-3-p2).

**Comment by slvrdlphn** [comment]
It still isn't resolved but I've already given up on it working. :( thank
you for trying to help,  though.
