### ISSUE TITLE
"Email download link" on Customer Home mobile card silently fails

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#777]
#### Steps to reproduce
1. Start logged out of the app, and sign up for a new account. (Or log in to an existing account with a site that has the Customer Home.)
2. After landing on the customer home, select "Email download link" on the "Go Mobile" card.

#### What I expected

I expected to get a link to download the app emailed to me.

#### What happened instead

No email arrived and no error appeared on screen.

However, I saw this console error:

```
Uncaught TypeError: __webpack_require__(...).logout is not a function
    at entry-main.js:2
    at 155.js:2
    at Request.callback (155.js:2)
    at Request.<anonymous> (155.js:2)
    at Request.Emitter.emit (155.js:2)
    at XMLHttpRequest.xhr.onreadystatechange (155.js:2)
```

#### App Version / OS version

WPDesktop 5.0.0-beta2 / macOS 10.15.3

#### Screenshot / Video

![Screenshot 2020-02-19 15 03 25](https://user-images.githubusercontent.com/8658164/74847162-96622380-5329-11ea-9b0e-f0a82e8ff9f6.png)

#### Context / Source
#manual-testing

cc @gwwar

**Comment by mmtr** [comment]
@rachelmcr did you use an a8c email? seems we don't support those according to https://github.com/Automattic/wp-calypso/pull/38960#issuecomment-576849576

**Comment by mmtr** [comment]
Seems the API request to `/auth/send-login-email` is failing on the desktop app:

<img width="618" alt="Screen Shot 2020-02-21 at 13 40 27" src="https://user-images.githubusercontent.com/1233880/75035469-d3582280-54af-11ea-97b4-4ef27fac78c8.png">

```
{"error":"invalid_token","message":"Bearer token not for specified client_id"}
```

**Comment by mmtr** [comment]
I think this is caused by a bug in the WordPress.com API HTTP Layer. In https://github.com/Automattic/wp-calypso/pull/38866 we moved the `/auth/send-login-email` calls  from `undocumented.js` to the data layer which apparently is not setting the auth token we are setting in `undocumented.js`.

https://github.com/Automattic/wp-calypso/blob/6a593a0d88df8d7622d82f31ce3503d3264f087c/client/lib/wpcom-undocumented/index.js#L38-L42

That token is loaded only for oAuth apps like the desktop app.

https://github.com/Automattic/wp-calypso/blob/6a593a0d88df8d7622d82f31ce3503d3264f087c/client/lib/wp/browser.js#L22-L23

cc @dmsnell

**Comment by mmtr** [comment]
Perhaps is something else. I tried adding the auth token in https://github.com/Automattic/wp-calypso/pull/39598, generated a local desktop build using those Calypso changes but the request still fails. I verified the request has an authorization header using the token returned by `oauthToken.getToken()`, so I have no idea why the API is rejecting it.

**Comment by kwight** [comment]
We confirmed the problem is a client ID mismatch, but while testing, I wasn't able to see why the mismatch was happening yet.

**Comment by mmtr** [comment]
Alright, I spent some time today and was able to identify this is part of a bigger issue causing the desktop app to don't be able to consume any API endpoint extending `WPCOM_JSON_API_Mobile_Apps_Only_Endpoint`. Note that this issue is not new and completely unrelated to https://github.com/Automattic/wp-calypso/pull/38866, since the desktop app has being using (or trying to) such endpoints for quite a while (i.e. email download link through the Me > Get apps in any previous version).

The problem is that the WP.com API is rejecting any request to endpoints extending `WPCOM_JSON_API_Mobile_Apps_Only_Endpoint` because those endpoints checks that the auth token belongs to the given `client_id`. Calypso uses [`wpcom_signup_id`](https://github.com/Automattic/wp-calypso/search?q=wpcom_signup_id&unscoped_q=wpcom_signup_id) ([`39911 `](https://github.com/Automattic/wp-calypso/blob/7e0f65ad3730c07c456c4974d3603b6ebc3e340b/config/production.json#L154)) which doesn't match the client id of the bearer auth token ([`43452`](https://github.com/Automattic/wp-desktop/blob/5c4d2db51a6af15b789cef531c894165bb6310d3/Makefile#L137)).

This could be solvable by using `desktop_oauth_client_id`/`desktop_oauth_client_secret`, but unfortunately these values are secret and not available in the client (meaning we cannot use `config( 'desktop_oauth_client_id' )` when doing a request). 

I guess [Calypso doesn't store secrets on the client config](https://github.com/Automattic/wp-calypso/blob/7e0f65ad3730c07c456c4974d3603b6ebc3e340b/client/server/config/parser.js#L69-L70) due to security concerns so any workaround should keep that info safe.

One option could be to bypass the `client_id` check in the API for requests coming from the desktop app, but I don't know if that would flag more security concerns.
