### ISSUE TITLE
Linux app not letting me sign in

### ISSUE THREAD

**Issue by derezion** [Automattic/wp-desktop#796]
#### Steps to reproduce
1. Launch WordPress.com app
2. See a screen with a feed of one of my tags and sign in/sign up links that direct to a browser

#### What I expected
Seeing my account.

#### What happened instead
Got a feed of one of my tags and sign in/sign up links that direct to a browser

#### App Version / OS version
5.0.0 / Ubuntu 16.04

#### Screenshot / Video
https://schooladvisor26.files.wordpress.com/2020/03/screenshot-from-2020-03-04-13-03-49-debrezion-wordpress-destkop.png?w=640

Inline-style: 
![alt text](https://schooladvisor26.files.wordpress.com/2020/03/screenshot-from-2020-03-04-13-03-49-debrezion-wordpress-destkop.png?w=640 "Screenshot of the app")

**Comment by derezion** [comment]
And I can't seem to uninstall the app through the Ubuntu Software Center. I wanted to see if reinstalling it would help.

**Comment by rachelmcr** [comment]
Thanks for the report! This is the same issue we're currently tracking in https://github.com/Automattic/wp-desktop/issues/400.

We don't yet have a solution for the underlying problem, but you should be able to resolve it by removing the app's supporting files. On Linux, this should be at `$XDG_CONFIG_HOME/Wordpress.com` or `~/.config/Wordpress.com`.

I'm going to close this issue since we're already tracking it, but please let us know if you continue to have trouble with this!
