### ISSUE TITLE
Implement i18n

### ISSUE THREAD

**Issue by mkaz** [Automattic/wp-desktop#8]
From @johngodley 

Looking at this some more it's a bit tricky.

Although the app semi-supports different locales, a proper locale is only set during the `wpcom_user_bootstrap` section of `server/pages/index.js` - this does not happen in the app as it is very much a WordPress.com browser thing.

In order for this to work in the app we would need to pass the users locale through to the Calypso server when it first renders the page, and use this in the desktop.jade context. Only then will isRTL be set.

**Comment by johngodley** [comment]
See also https://github.com/Automattic/wp-desktop/issues/19

**Comment by mjangda** [comment]
Looks like we can just use any node i18n lib for translation and electron has an `app.getLocale()` function we can use to get the current system language. Might make sense to reuse calypso's i18n mixin with a few tweaks:

- If the user is logged out, default to the system language.
- If the user is logged in, use their selected language (there may be some timing issues here between when user bootstrap runs and when electron sets up all the UI elements)
- Bundle the translations with the app (to avoid the remote lookup). We'd need a script during packaging that fetches the remote translations.

**Comment by mjangda** [comment]
@deBhal would love a sanity check on this. Any concerns with using the i18n mixin directly in the desktop app? A quick test shows it works but wasn't sure if I should be aware of any caveats.

**Comment by deBhal** [comment]
@mjangda The i18n mixin is designed to work as a module independent of react, so it should work just fine.  It just needs to know what locale to load, and it will take care of the rest.

I'm not sure how much the desktop app deviates from the web client, but we normally initialize the i18n module out of [client/boot](https://github.com/Automattic/wp-calypso/blob/master/client/boot/index.js#L147).  If it's already working, you should be good to go :)

As a potential optimization for down the track, we've got some "bootstrap" logic that we use for dev that might be appropriate to repurpose for desktop.  It's a mechanism that lets you pass the translation strings to the module instead of having it pull them down over the net.  We use it in the dev config for a faster startup.  It's good to download the strings periodically to pick up the latest translations, but there's be an opportunity there to cache the data locally.  It might be just the ticket for offline use.
