### ISSUE TITLE
The app is showing numerous sites as requiring updates, but all plugins are up-to-date

### ISSUE THREAD

**Issue by colbydnn** [Automattic/wp-desktop#862]
#### Steps to reproduce
1. Open Wordpress.com app
2. Multiple sites showing that updates are required
3. Go to Plugins - Updates, shows no updates required
4. Go to Activities and it shows numerous updates required

#### What I expected
Site should not be showing that updates are required

#### What happened instead
No updates are required but App is showing that updates are required (iOS app is also showing this)

#### App Version / OS version
App 4.4.1 on Windows 10
iOS App version 14.6 on iOS 13.4.1

#### Screenshot / Video
![image](https://user-images.githubusercontent.com/9012379/80009898-b03df500-8497-11ea-80f7-d918f0641554.png)
![image](https://user-images.githubusercontent.com/9012379/80009949-bd5ae400-8497-11ea-881f-806b14169be2.png)

**Comment by designsimply** [comment]
You shouldn't see an update button for a plugin on the plugin detail screen in Plugins > Manage if the app is already up-to-date, but the activity stream will still show the update notice for past events if they are dated in the past (which is showing in the first screenshot you included).

I tested viewing plugins needing updates compared to what they look like after they have been updated with WPiOS 15.0.0.0 on iOS 13.4.1 and with WPDesktop 5.2.0 on Windows 10 and couldn't get any plugins to show that an update is needed for the same version that is installed like you have showing in your second screenshot.

Video 1: [3m13s](https://cloudup.com/cFdWJGTG9Wk) (WPiOS app)
Video 2: [4m5s](https://cloudup.com/c89OQFl5nCv) (WPDesktop app)
<p style="clear:both;"><sup>Tested with WPiOS 15.0.0.0 TestFlight beta on iPhone 11 iOS 13.4.1 and WPDesktop 5.2.0 on Windows 10.</sup></p>

I think this has either been resolved or something was off in the caching for your plugin page at the time you checked on the plugin updates when you first reported this issue. Because I wasn't able to replicate the same problem in a test and because we've had a few version updates since that time, I am going to close this issue. If you're still having trouble though, please reply here to let me know and I will re-open the issue to investigate!
