### ISSUE TITLE
Clicking “View Post” after updating a post or page locks the user out of the main UI

### ISSUE THREAD

**Issue by robertocyrino** [Automattic/wp-desktop#908]
#### Steps to reproduce
1. Editor: open a post or page
2. Make a change
3. Click **Update**
4. Click **View post** (snackbar on the lower left)
5. Confirm to be unable to return to the main UI without quitting the app

#### What I expected
Upon clicking "View Post", a new browser window should be opened.

#### What happened instead
The post opened in the app window with no way back to the main UI.

#### App Version / OS version
6.0.0-beta2 - Mac OS 10.13

#### Screenshot / Video
https://cloudup.com/cEcGroUU_Vg

#### Context / Source
https://apptestingo2.wordpress.com/2020/06/11/to-test-wordpress-com-desktop-6-0-0/#comment-5072

#manual-testing #dogfooding

**Comment by nsakaimbo** [comment]
I believe what's happening here is that `View Post` takes the user out of the iframe context, and therefore the connection to Electron and iframed Calypso is lost. All keyboard shortcuts cease to work, and clicking on items in the sidebar panel will take us to a browser, instead of remaining in-app.

I would venture to guess this bug has been in the app for a long time, and isn't newly-introduced behavior.

At the very least, clicking `View Post` should automatically redirect the user to an external browser so they aren't left in a bad state. Still trying to debug further.

cc: @designsimply
