### ISSUE TITLE
Plan: Checklist never loads on My Plan page for Jetpack site

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/wp-desktop#942]
#### Steps to reproduce
1. On the web, create a Jetpack site and connect it to a WordPress.com account.
2. Log in to that WordPress.com account in the desktop app.
3. Go to the My Sites section and select the Jetpack site.
4. Select Plan in the sidebar to open the My Plan page.

#### What I expected

I expected the My Plan page to load with a checklist in the My Checklist section.

#### What happened instead

The My Checklist section appears but the checklist never loads; placeholders remain there indefinitely.

#### App Version / OS version

WPDesktop 6.0.1-beta2 / macOS 10.15.5

I compared with web behavior in Chrome and confirmed the issue is specific to the app. I also tested with an existing as well as a brand new Jetpack site and confirmed the same behavior on both sites.

#### Screenshot / Video

Checklist in the desktop app|Checklist on the web (expected)
-|-
![Screenshot 2020-07-16 10 42 27](https://user-images.githubusercontent.com/8658164/87656593-9a1b9a00-c751-11ea-9916-ec762411feae.png)|![Screenshot 2020-07-16 10 42 44](https://user-images.githubusercontent.com/8658164/87656602-9b4cc700-c751-11ea-8ef4-a0132ce9ac2a.png)

#### Context / Source
#beta-testing

**Comment by nsakaimbo** [comment]
This regression looks potentially related to Automattic/wp-calypso#44101? @cpapazoglou Could you please help take a look? Now you can build and run the desktop app completely from within Calypso by running `yarn run build-desktop` from the root of the repo.

**Comment by cpapazoglou** [comment]
@nsakaimbo It is definitely related and actually fixed in https://github.com/Automattic/wp-calypso/pull/44101 and I am sorry for the inconvenience 😢 . 

Running `yarn run build-desktop` in my master branch of Calypso produces the following

![](https://cln.sh/zjCpOO+)

It seems that the desktop app is synced with a branch that doesn't include https://github.com/Automattic/wp-calypso/pull/44101 which makes sense cause the latest commit in 

https://github.com/Automattic/wp-calypso/tree/1c032246c7f43addd773bc22eb75cdcf4bdd67ff

is 12 days ago (that should be Friday)

whereas https://github.com/Automattic/wp-calypso/pull/44101 was merged 9 days ago (that was Monday)

- Is there a process where I can help? 
- Was I supposed to notify / label that PR so that you are notified about the bug fix? 
- Should I merge https://github.com/Automattic/wp-calypso/pull/44101 to https://github.com/Automattic/wp-calypso/tree/1c032246c7f43addd773bc22eb75cdcf4bdd67ff ?

**Comment by nsakaimbo** [comment]
Hi, @cpapazoglou! Thanks for the follow-up and additional context, and no worries. Glad the issue was fixed in a subsequent commit already. 

I created a branch in Calypso `desktop/release/6.0.1` with the SHA of the existing desktop release submodule and merged your change into it. I tested it with the desktop app and confirmed your patch restores the checklist. 🎉  Opened a PR to merge the patch into wp-desktop: #946. 

We anticipate that our _next_ release will deprecate the separate wp-desktop repo and submodule (i.e. we'll soon be deploying directly from within Calypso), which should hopefully make things a lot more in sync going forward.

**Comment by cpapazoglou** [comment]
> We anticipate that our _next_ release will deprecate the separate wp-desktop repo and submodule (i.e. we'll soon be deploying directly from within Calypso), which should hopefully make things a lot more in sync going forward.

That's great news! I didn't even know that the code is shared with wp-desktop.. It will make things more transparent!

**Comment by nsakaimbo** [comment]
Fixed by #946.
