### ISSUE TITLE
Mac: Smart quotes do not appear when enabled on Mac settings

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/wp-desktop#950]
#### Steps to reproduce

- Enable the smart quotes feature on Mac settings.
- Compose a post/page with Mac desktop app.
- Click on the quote key on keyboard.

#### What I expected

A smart quote appears.

#### What happened instead

The regular quote appears instead.

#### App Version / OS version

- 6.0.1. 
- Mac OS 10.15.6

#### Screenshot / Video

<img width="230" alt="Screenshot 2020-08-08 at 4 29 47 PM" src="https://user-images.githubusercontent.com/18581859/89708393-615b9300-d994-11ea-81b5-437dc1b713ab.png">

<img width="636" alt="Screenshot 2020-08-08 at 4 31 20 PM" src="https://user-images.githubusercontent.com/18581859/89708420-99fb6c80-d994-11ea-96d8-ad931cb1c1f9.png">

<img width="780" alt="Screenshot 2020-08-08 at 4 31 37 PM" src="https://user-images.githubusercontent.com/18581859/89708422-a1bb1100-d994-11ea-81e5-cc469e7fb3f8.png">

#### Notes

- Happens on both Calypso and Gutenberg editors.
- On the same site, same post/page - using browsers, the smart quote appears.

#### Context / Source

#user-report

**Comment by arunsathiya** [comment]
3208137-zen

**Comment by nsakaimbo** [comment]
Update on this thread: this issue is not specific to the Desktop application. In fact, it appears that smart quotes do not work in Chromium-based browsers in general - you can confirm this by trying to use smart quotes in Google Chrome, for example.

We may be able to work around this in Electron by using something like https://github.com/CharlieHess/electron-text-substitutions (that particular library hasn't been updated in a while but perhaps we can glean something from its implementation, at the very least.
