### ISSUE TITLE
Windows App: App does not fully close when clicking the `x` icon to close the app

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/wp-desktop#967]
Our customer initially reported that the Windows App wasn't closing fully, and that this prevented them from re-opening the app after they thought they closed the app. They explained as follows:

>Versions 6+ start without a problem, but after I close, it can not restart unless I kill a hidden process.. as a programmer I believe I know what is happening, but exactly why I cannot tell.

We determined that the customer was using version 6.0.2, and recommended that they update to version 6.5. We also explained that the app closes to the Windows system tray when closing the app.

This didn't resolve the issue entirely. 

#### Steps to reproduce

The customer provided the following steps to reproduce the issue:

1. I start the application from a Windows shortcut, I may work a bit
2. I close by clicking on the ‘x’ in the top right hand corner of the window
3. I try to start again from the same Windows shortcut, a brief hourglass but nothing happens
4. But, File / Quit works, ...

#### What I expected

Clicking on the `x` icon typically used to close Windows app, should close the WordPress.com Desktop App.

#### What happened instead

Instead, clicking on the `x` doesn't close the app fully, and prevents the customer from opening the app again. The customer also stated the following:

>Having to go to the tray and restore from there is obviously not acceptable.

#### App Version / OS version

WordPress.com Desktop App: v6.5 for Windows
Windows 10, 64bit

#### Context / Source

This is a customer report in 3534422-zen

**Comment by kriskarkoski** [comment]
Another report in 3898204-zen

**Comment by nsakaimbo** [comment]
Update on this thread: this behavior is intentional and is consistent with how the "Close" button behaves on other platforms. However, we did recently refine the behavior so that double-clicking the application shortcut restores the app more consistently after its hidden to the system tray.

The latest build can now be downloaded at the WordPress Desktop landing page [here](https://fieldguide.automattic.com/desktop-app/) (please install version 7.2.0 or greater).
